### ISSUE TITLE
How does this help with gulp?

### ISSUE THREAD

**Issue by kingbuzzman** [JeNeSuisPasDave/using-virtual-environments#1]
This is not an issue: (i just didn't know how else to get ahold of you 😜)

So gulp is only allowed to be installed locally, and then you can use gulp-cli to reference it globally but at the end of the day you still installed it locally and you have a node_modules somewhere in your directories.

So i guess the issue i have is pretty apparent, i have a virtualenv and i stuck node inside it, but i can't seem to get away from polluting my fronted dir(`www/`) with a node_module because of gulp no matter how i try and install it into the virtualenv...

Any help will be appreciated.

**Comment by JeNeSuisPasDave** [comment]
_(Note: my contact info is in the about page of the blog, or you can post comments to the blog post ... this kind of question would be appropriate to post as a comment.)_

I use gulp as well, also to drive 'builds' of websites. For instance, the [blog](https://www.develves.net/blogs/asd/) is built with gulp. But I don't use gulp-cli.

For each project I open a terminal window, cd to the project root folder, and then activate the virtual environment ... that environment (i.e. the local node installation) is only available from that terminal window. If I open a different terminal window then that new terminal window 'knows' nothing about the virtual environment.

Virtual environments aren't designed or intended for global use. Because virtual environments use environment variables to redirect node to the local project-specific node installation, virtual environments are inherently specific to a particular process (and it's child processes) . This is also true for Python virtual environments and ruby virtual environments).
